<br>
<hr>
<br>
<p class="text-center muted">&copy; Copyright 2017 Bitvest | <a href=''>Terms &amp; Conditions</a> | <a href=''>Privacy Policy</a> | <a href=''>About Us</a> | <a href=''>Contact</a></p>
    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="<?=$vars['baseUrl']?>/bootstrap/js/jquery-3.1.1.min.js"></script>
    <script src="<?=$vars['baseUrl']?>/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>