<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bitvest.org - Bitcoin Jobs &amp; Stocks</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="<?=$vars['baseUrl']?>/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <!-- Le styles -->
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="<?=$vars['baseUrl']?>/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="<?=$vars['baseUrl']?>/favicon.ico" type="image/x-icon">
</head>
<body>    
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="">Bitvest.org</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              
              <?php 
              $links = $vars['menu']->getLinks();
              foreach ($links as $i => $link) {   
                  if ($vars['route'] == 'index/index') {
                      $vars['route'] = '';
                  }
                  if ($vars['route'] == $link['route']) {
                      echo "<li class=\"active\">";
                  } else {
                      echo "<li>";
                  }
                  echo "<a href=\"{$vars['baseUrl']}/{$link['route']}\">";
                  echo $link['label'];
                  echo "</a>";
                  echo "</li>";
              }
              ?>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!-- /.container -->
      </div><!-- /.navbar-inner -->
    </div><!-- /.navbar -->

    <div class="container">

