<?php include(__DIR__ . '/../header.phtml'); ?>

<h3 class="muted">User &raquo; Forgot password</h3>

<div>
    <p>
        Enter your email address below, and we'll send you a link to reset your password.
    </p>
</div>

<form class="form-horizontal" method="post" action="<?=$vars['baseUrl']?>/user/forgot-password-submit">
  <div class="control-group">
    <label class="control-label" for="inputEmail">Email</label>
    <div class="controls">
      <input type="text" id="inputEmail" name="email" placeholder="Email" value="<?=$vars['formValues']['email']?>">
      <div style='color:red'><?=$vars['formErrors']['email']?></div>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">Send password reset link</button>
    </div>
  </div>
</form>


<?php include(__DIR__ . '/../footer.phtml'); ?>
