<?php include(__DIR__ . '/../header.phtml'); ?>

<h3 class="muted">User &raquo; Reset password</h3>

<div>
    <p>
        Enter a new password below.
    </p>
</div>

<form class="form-horizontal" method="post" action="<?=$vars['baseUrl']?>/user/password-reset-submit">
  <div class="control-group">
    <label class="control-label" for="inputPassword">Password</label>
    <div class="controls">
      <input type="password" id="inputPassword" name="password" placeholder="Password" value="<?=$vars['formValues']['password']?>">
      <div style='color:red'><?=$vars['formErrors']['password']?></div>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputConfirmPassword">Confirm password</label>
    <div class="controls">
      <input type="password" id="inputConfirmPassword" name="confirmPassword" placeholder="Confirm password" value="<?=$vars['formValues']['confirmPassword']?>">
      <div style='color:red'><?=$vars['formErrors']['confirmPassword']?></div>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">Update password</button>
    </div>
  </div>
  <input type="hidden" name="email" value="<?=$vars['formValues']['email']?>">
  <input type="hidden" name="passwordResetCode" value="<?=$vars['formValues']['passwordResetCode']?>">  
</form>


<?php include(__DIR__ . '/../footer.phtml'); ?>
