<?php include(__DIR__ . '/../header.phtml'); ?>

<h3 class="muted">User &raquo; Signup</h3>

<form class="form-horizontal" method="post" action="<?=$vars['baseUrl']?>/user/signup-submit">
  <div class="control-group">
    <label class="control-label" for="inputEmail">Email</label>
    <div class="controls">
      <input type="text" id="inputEmail" name="email" placeholder="Email" value="<?=$vars['formValues']['email']?>">
      <div style='color:red'><?=$vars['formErrors']['email']?></div>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputPassword">Password</label>
    <div class="controls">
        <input type="password" id="inputPassword" name="password" placeholder="New password"> <span class='muted'>(minimum 5 characters)</span>
      <div style='color:red'><?=$vars['formErrors']['password']?></div>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">Create account</button>
    </div>
  </div>
</form>

<?php include(__DIR__ . '/../footer.phtml'); ?>
